/*
AUTOGENERATED!
*/

import "dotenv/config";
import { startServer } from "@csi-foxbyte/fastify-toab";

import config from "../../fastify-toab.config.js";

startServer(import.meta.resolve("./registries.js"), import.meta.resolve("../instrumentation.js"), config).catch((err) => {
    console.error(err);
    process.exit(1)
});