/*
AUTOGENERATED
*/

import { InferService, ServiceContainer, WorkerContainer, QueueContainer } from "@csi-foxbyte/fastify-toab";

import testService from "../test/test.service.js";

export type TestService = InferService<typeof testService>;

export function getTestService(deps: ServiceContainer) {
    return deps.get<TestService>(testService.name);
}

