/*
AUTOGENERATED
*/

import { InferService, ServiceContainer, WorkerContainer, QueueContainer } from "@csi-foxbyte/fastify-toab";

import testService from "../test/test.service.js";
import testDoStuffWorker from "../test/workers/doStuff.worker.js";

export type TestService = InferService<typeof testService>;
export type TestDoStuffWorker = (typeof testDoStuffWorker)["worker"];
export type TestDoStuffWorkerQueue = (typeof testDoStuffWorker)["queue"];
export type TestDoStuffWorkerJob = (typeof testDoStuffWorker)["job"];

export function getTestService(deps: ServiceContainer) {
    return deps.get<TestService>(testService.name);
}
export function getTestDoStuffWorker(deps: WorkerContainer) {
  return deps.get<TestDoStuffWorker>(testDoStuffWorker.queueName);
}
export function getTestDoStuffWorkerQueue(deps: QueueContainer) {
  return deps.get<TestDoStuffWorkerQueue>(testDoStuffWorker.queueName);
}

