/*
AUTOGENERATED!
*/

import {
  ControllerRegistry,
  ServiceRegistry,
  WorkerRegistry,
} from "@csi-foxbyte/fastify-toab";

export async function getRegistries(dontInitializeWorkers?: boolean) {
  let workerRegistryRef: { current: WorkerRegistry | null } = {
    current: null,
  };

  const serviceRegistry = new ServiceRegistry(workerRegistryRef);


  const workerRegistry = new WorkerRegistry(serviceRegistry);

  workerRegistryRef.current = workerRegistry;

  await workerRegistry.resumeQueues();

  const controllerRegistry = new ControllerRegistry(serviceRegistry);


  return { controllerRegistry, serviceRegistry, workerRegistry };
}

/**
 * Use this function inside a sandboxedWorker to gain access to services and other workers.
 */
export async function initializeContainers() {
  const { serviceRegistry, workerRegistry } = await getRegistries(true);

  return {
    services: serviceRegistry.resolve(),
    queues: { get: workerRegistry.getQueue.bind(workerRegistry) },
  };
}
