import fg from "fast-glob";
import { capitalize } from "../helpers.js";
import { sep } from "path";
import { RunTemplate } from "./templates.js";

export async function createRun() {
    return RunTemplate({});
};

export async function createInternals(workdir: string) {
    const services = await fg("**/*.service.ts", { cwd: workdir });
    const workers = await fg("**/*.worker.ts", { cwd: workdir });

    let generated = `/*
AUTOGENERATED
*/

import { InferService, ServiceContainer, WorkerContainer, QueueContainer } from "@csi-foxbyte/fastify-toab";

`;

    let types = "";

    let imports = "";

    let getters = "";

    for (const service of services) {
        const serviceName = service
            .split(".")
            .slice(-3)[0]
            .split(sep)
            .slice(-1)[0];
        const serviceNameTypeName = `${capitalize(serviceName)}Service`;
        imports += `import ${serviceName}Service from "../${serviceName}/${serviceName}.service.js";\n`;

        types += `export type ${serviceNameTypeName} = InferService<typeof ${serviceName}Service>;\n`;

        getters += `export function get${serviceNameTypeName}(deps: ServiceContainer) {
    return deps.get<${serviceNameTypeName}>(${serviceName}Service.name);
}\n`;
    }

    for (const worker of workers) {
        const componentName = worker.split(sep).slice(-3)[0];

        const workerName = worker
            .split(".")
            .slice(-3)[0]
            .split(sep)
            .slice(-1)[0];

        const workerNameImported = `${componentName}${capitalize(
            workerName
        )}Worker`;

        const workerNameTypeBase = capitalize(workerNameImported);

        imports += `import ${workerNameImported} from "../${componentName}/workers/${workerName}.worker.js";\n`;

        types += `export type ${workerNameTypeBase} = (typeof ${workerNameImported})["worker"];\n`;
        types += `export type ${workerNameTypeBase}Queue = (typeof ${workerNameImported})["queue"];\n`;
        types += `export type ${workerNameTypeBase}Job = (typeof ${workerNameImported})["job"];\n`;

        getters += `export function get${workerNameTypeBase}(deps: WorkerContainer) {
  return deps.get<${workerNameTypeBase}>(${workerNameImported}.queueName);
}\n`;
        getters += `export function get${workerNameTypeBase}Queue(deps: QueueContainer) {
  return deps.get<${workerNameTypeBase}Queue>(${workerNameImported}.queueName);
}\n`;
    }

    generated += imports + "\n";
    generated += types + "\n";
    generated += getters + "\n";

    return generated;
}

export async function createRegistries(
    workdir: string,
) {
    const services = await fg("**/*.service.ts", { cwd: workdir });
    const controllers = await fg("**/*.controller.ts", { cwd: workdir });
    const workers = await fg("**/*.worker.ts", { cwd: workdir });

    let generated = `/*
AUTOGENERATED!
*/

import {
  ControllerRegistry,
  ServiceRegistry,
  WorkerRegistry,
} from "@csi-foxbyte/fastify-toab";`;

    function mapImport({ id, path }: { path: string; id: string }) {
        return `import ${id} from "../${path
            .split(".")
            .slice(0, -1)
            .join(".")
            .split(sep)
            .join("/")}.js";`;
    }

    function mapIdAndPath(path: string) {
        return {
            path,
            id: path.split(sep).join("_").split(".").slice(0, -1).join("$"),
        };
    }

    const servicesNameAndPath = services.map(mapIdAndPath);
    const workersNameAndPath = workers.map(mapIdAndPath);
    const controllersNameAndPath = controllers.map(mapIdAndPath);

    generated += "\n"

    generated += servicesNameAndPath
        .map(mapImport)
        .concat(workersNameAndPath.map(mapImport))
        .concat(controllersNameAndPath.map(mapImport))
        .join("\n");

    generated += "\n";

    generated += `
let serviceRegistry: ServiceRegistry | null = null;
let workerRegistry: WorkerRegistry | null = null;
let controllerRegistry: ControllerRegistry | null = null;

export async function getRegistries(dontInitializeWorkers?: boolean) {
  if (serviceRegistry !== null && workerRegistry !== null && controllerRegistry !== null) return { controllerRegistry, serviceRegistry, workerRegistry };

  let workerRegistryRef: { current: WorkerRegistry | null } = {
    current: null,
  };

  serviceRegistry = new ServiceRegistry(workerRegistryRef);
${servicesNameAndPath
            .map(({ id }) => `  serviceRegistry.register(${id});`)
            .join("\n")}

  workerRegistry = new WorkerRegistry(serviceRegistry);
  if (!dontInitializeWorkers) {
${workersNameAndPath
            .map(
                ({ id }) => `   await workerRegistry.register(${id}, dontInitializeWorkers);`
            )
            .join("\n")}
  };

  workerRegistryRef.current = workerRegistry;

  await workerRegistry.resumeQueues();

  controllerRegistry = new ControllerRegistry(serviceRegistry);
${controllersNameAndPath
            .map(({ id }) => `  controllerRegistry.register(${id});`)
            .join("\n")}

  return { controllerRegistry, serviceRegistry, workerRegistry };
}

/**
 * Use this function inside a sandboxedWorker to gain access to services and other workers.
 */
export async function initializeContainers() {
  const { serviceRegistry, workerRegistry } = await getRegistries(true);

  return {
    services: serviceRegistry.resolve(),
    queues: { get: workerRegistry.getQueue.bind(workerRegistry) },
  };
}
`;

    return generated;
}
