import Handlebars from "handlebars";

export const MiddlewareTemplate =
    Handlebars.compile(`import { createMiddleware } from "@csi-foxbyte/fastify-toab";

export const {{lname}}Middleware = createMiddleware(async ({ ctx }, next) => {
  const newCtx = { ...ctx, /** your extra data */};

  await next({ ctx: newCtx });

  return newCtx;
});
`);

export const WorkerTemplate =
    Handlebars.compile(`import { createWorker } from "@csi-foxbyte/fastify-toab";
import { Job } from "bullmq";
import defaultConnection from "../../connection.js";

const {{lname}}Worker = createWorker()
    .queue("{{qname}}")
    .job<Job<{}, {}>>()
    .connection(defaultConnection)
    .processor(async () => {
        return {};
    });

/*
AUTOGENERATED!
*/

export default {{lname}}Worker;
`);

export const SandboxedWorkerTemplate0 =
    Handlebars.compile(`import { createWorker } from "@csi-foxbyte/fastify-toab";
import { SandboxedJob } from "bullmq";
import defaultConnection from "../../connection.js";

const {{lname}}Worker = createWorker()
    .queue("{{qname}}")
    .sandboxedJob<SandboxedJob<{}, void>>()
    .connection(defaultConnection)
    .processor(new URL("./{{mlname}}/workers/{{lname}}.sandboxedWorker.js", import.meta.url));

/*
AUTOGENERATED!
*/

export default {{lname}}Worker;
`);

export const SandboxedWorkerTemplate1 = Handlebars.compile(`import "dotenv/config";
import type { {{tname}}WorkerJob } from "../../@internals/index.js";
import { initializeContainers } from "../../@internals/registries.js";

export default async function run(
  job: {{tname}}WorkerJob
): Promise<{{tname}}WorkerJob["returnValue"]> {
  const { services } = await initializeContainers();
}
`);

export const ControllerTemplate =
    Handlebars.compile(`import { createController } from "@csi-foxbyte/fastify-toab";

const {{lname}}Controller = createController()
    .rootPath("/{{lname}}")

/*
AUTOGENERATED!
*/

export default {{lname}}Controller;
`);

export const ServiceTemplate = Handlebars.compile(`import { createService } from "@csi-foxbyte/fastify-toab";

const {{lname}}Service = createService("{{lname}}", async () => {
    // Your code here...
});

/*
AUTOGENERATED!
*/

export default {{lname}}Service;
`);


export const TestTemplate = Handlebars.compile(`import test, { describe, it, mock } from "node:test";

test("{{lname}}.service", {}, (t) => {
    // Your tests here
});
`);

export const RunTemplate = Handlebars.compile(`/*
AUTOGENERATED!
*/

import "dotenv/config";
import { startServer } from "@csi-foxbyte/fastify-toab";

import config from "../../fastify-toab.config.js";

startServer(import.meta.resolve("./registries.js"), import.meta.resolve("../instrumentation.js"), config).catch((err) => {
    console.error(err);
    process.exit(1)
});`);