import { createWorker } from "@csi-foxbyte/fastify-toab";
import { Job } from "bullmq";
import defaultConnection from "../../connection.js";

const doStuffWorker = createWorker()
    .queue("{test-doStuff-queue}")
    .job<Job<{}, {}>>()
    .connection(defaultConnection)
    .processor(async () => {
        return {};
    });

/*
AUTOGENERATED!
*/

export default doStuffWorker;
